In [8]:
# 3계층 신경망에서 신호의 전달 방법
import numpy as np

def sigmoid_function(x):
    return 1 / (1+np.exp(-x))

In [9]:
# 입력 -> 은닉 -> 출력 순전파 
# 입력
I = np.array([0.9, 0.1, 0.8])
print("입력:\n", I)
# 입력층 -> 은닉층으로 신호 전달을 위해 가중치 행렬 
W_i_h = np.array([
    [0.9, 0.3, 0.4], # 은닉층 1번 노드로 전달되는 가중치 
    [0.2, 0.8, 0.2],
    [0.1, 0.5, 0.6]
])
print("가중치 (입력층 -> 은닉층):\n", W_i_h)
# 은닉층 -> 출력층 신호 전달을 위한 가중치
W_h_o = np.array([
    [0.3, 0.7, 0.5],
    [0.6, 0.5, 0.2],
    [0.8, 0.1, 0.9]
])
print("가중치 (은닉층 -> 출력층):\n", W_h_o)

입력:
 [0.9 0.1 0.8]
가중치 (입력층 -> 은닉층):
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
가중치 (은닉층 -> 출력층):
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [10]:
# 입력층의 입력에 입력층의 가중치를 곱해서 합한 값  -> 은닉계층의 입력값
X_h = np.dot(W_i_h, I) # 내적곱
print("X hidden:\n", X_h)

X hidden:
 [1.16 0.42 0.62]


In [11]:
# 은닉계층의 출력값 : 활성화 함수를 적용, 다음레이어의 입력값으로 전달
O_h = sigmoid_function(X_h)
print("hidden 레이어의 출력:\n", O_h)

hidden 레이어의 출력:
 [0.76133271 0.60348325 0.65021855]


In [12]:
# 출력레이어 
X_o = np.dot(W_h_o, O_h) # 이전 레이어 출력값을 입력으로 점곱
print("출력 계층의 입력값:\n", X_o)

출력 계층의 입력값:
 [0.97594736 0.88858496 1.25461119]


In [14]:
# 출력계층의 활성화 함수 적용
O_o = sigmoid_function(X_o)
print("최종 출력:", O_o)

최종 출력: [0.72630335 0.70859807 0.77809706]
